dbmdz/solr-ocrhighlighting

- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/test/java/org/mdz/search/solrocr/solr/HocrEscapedTest.java
Previously, we would truncate a OCR snippet before we extracted the page number from the snippet. In some cases, this lead to the page number being truncated, leading to a missing page number in the results.
The PR addresses this by first extracting the page number and then truncating the snippet for further parsing.
> Fix bug that caused page numbers to be missed

- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/test/java/org/mdz/search/solrocr/solr/OcrFieldsTest.java
- src/test/java/org/mdz/search/solrocr/solr/Utf8OcrFieldsTest.java
Also fixes improper truncation in MiniOCR as a nice side-effect.
The unit tests had to be changed for MiniOCR, since they had encoded the bad truncation in the assertions.
> Refactor fragment truncation logic for more code-reuse

- README.md
- src/main/java/org/mdz/search/solrocr/formats/OcrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoFormat.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/solr/OcrHighlightParams.java
- src/main/java/org/mdz/search/solrocr/solr/SolrOcrHighlighter.java
- src/test/java/org/mdz/search/solrocr/solr/HocrEscapedTest.java
This PR adds a new query-time option `hl.absoluteHighlights` that will make the plugin return **absolute** coordinates for highlighted regions, i.e. coordinates that are relative to the containing page, not the containing snippet.
> Add support for hl.absoluteHighlights option (implements #6)

- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/util/OcrBox.java
Previously the three supported formats had a lot of very similar code to parse their respective formats and generate snippets and highlight spans.
> Refactor snippet parsing across formats to increase code reuse

- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrClassBreakIterator.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrPassageFormatter.java
Previously `BLOCK` would only map to `ocr_carea` and `LINE` only to `ocr_line`. With this PR, `ocrx_block` and `ocrx_line` are now also acceptable values for these generic block types.
> hocr: Allow multiple implementations of generic block types (fixes #20)

- src/main/java/org/mdz/search/solrocr/formats/OcrBlock.java
- src/main/java/org/mdz/search/solrocr/formats/OcrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoFormat.java
- src/main/java/org/mdz/search/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrFormat.java
- src/main/java/org/mdz/search/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/lucene/OcrHighlighter.java
- src/main/java/org/mdz/search/solrocr/solr/SolrOcrHighlighter.java
- src/main/java/org/mdz/search/solrocr/util/ContextBreakIterator.java
- src/test/java/org/mdz/search/solrocr/solr/HocrEscapedTest.java
- src/test/java/org/mdz/search/solrocr/solr/OcrFieldsTest.java
- src/test/java/org/mdz/search/solrocr/solr/Utf8OcrFieldsTest.java
- src/test/java/org/mdz/search/solrocr/util/ContextBreakIteratorTest.java
Changes:
- No longer truncate fragments, the passages are now created in a way that prevents the crossing of the user-defined limits. The previous approach led to hard-to-track bugs, where we would either swallow some highlights or merge highlights from multiple pages
- No longer return any snippets for `*` queries
- Simplify internal APIs
> Refactor block-limitation logic to fix bugs and inconsistencies

- src/main/java/org/mdz/search/solrocr/formats/alto/AltoPassageFormatter.java
- src/test/java/org/mdz/search/solrocr/solr/AltoEscapedTest.java
- src/test/resources/data/alto_escaped.xml
The ">?" at the end of the regexp in the getTextFromXml return block was causing inline entities to not be correctly matched/removed. Removing the quantifier fixes this.
Results with error:
With patch:
XML used for testing (snipped from larger file for testing. The whole file can be provided if required):
```xml
<Page WIDTH="2092" HEIGHT="3850" PHYSICAL_IMG_NR="6" ID="page_6"> <TextBlock ID="block_12" HPOS="83" VPOS="3284" WIDTH="1703" HEIGHT="100"><TextLine ID="line_43" HPOS="182" VPOS="3284" WIDTH="1604" HEIGHT="49"><String ID="string_493" HPOS="706" VPOS="3285" WIDTH="222" HEIGHT="37" WC="0.72" CONTENT="Permanent"/><SP WIDTH="31" VPOS="3285" HPOS="928"/><String ID="string_494" HPOS="959" VPOS="3285" WIDTH="216" HEIGHT="36" WC="0.95" CONTENT="Committee"/><SP WIDTH="30" VPOS="3285" …
```
> Fix ALTO regexp to correctly match TextBlock/Page/etc entities

- src/main/java/org/mdz/search/solrocr/formats/alto/AltoCharFilterFactory.java
- src/test/resources/solr/alto-escaped/schema.xml
- Get rid of trailing `</>` tags after HTML stripping
- Combine all ALTO filtering into `AltoCharFilterFactory`, no more need for an explicit subsequent `HTMLStripCharFilter` in the analyzer chain
Many thanks to @mbennett-uoe for the helpful discussion!
> Fix bugs in ALTO handling

- src/main/java/org/mdz/search/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/org/mdz/search/solrocr/util/MultiFileBytesCharIterator.java
- src/main/java/org/mdz/search/solrocr/util/Utf8.java
Versions of Solr that ship with an ancient Guava (<16) fail to load the plugin because of the missing `Utf8` utility class. We now vendor this class to maintain compatiblity.
> Vendor Guava Utf8 util for compatiblity with older Solr versions

- src/main/java/org/mdz/search/solrocr/solr/SolrOcrHighlighter.java
Highlighter is  always giving null pointer exception when using non external field. added null check
> fix null pointer exception  when selecting  non external field

- src/main/java/org/mdz/search/solrocr/formats/OcrPassageFormatter.java
- src/main/java/org/mdz/search/solrocr/lucene/fieldloader/PathFieldLoader.java
- src/main/java/org/mdz/search/solrocr/util/FileBytesCharIterator.java
- src/main/java/org/mdz/search/solrocr/util/IterableCharSequence.java
- src/main/java/org/mdz/search/solrocr/util/MultiFileBytesCharIterator.java
- `IndexOutOfBoundsExceptions` are now logged as errors (i.e. they won't cause the request to fail) and contain more context to aid in debugging
- `FileNotFoundExceptions` now cause the request to fail (but include enough context to debug the issue).
> Better error reporting

- src/main/java/de/digitalcollections/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/de/digitalcollections/solrocr/util/OcrHighlightResult.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrEscapedTest.java
Previously a passage would be determined by the context of the first
match it contained (e.g. previous two lines + line with match + next two
lines). This caused breakage in cases where another match occurred on
the last line of the previous match's context.
We now expand the passage to the end of the last match's context.
Additionally, the end of a context is now determined based on the end of
the match, not the start. This will add one or multiple additional
context lines for matches that span multiple lines.
> Fix calculation of passages with matches spanning multiple lines

- docs/getting_started.md
- src/main/java/de/digitalcollections/solrocr/solr/HighlightComponent.java
- src/main/java/de/digitalcollections/solrocr/solr/SolrOcrHighlighter.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiUtf8Test.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoUtf8Test.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrUtf8Test.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrEscapedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrUtf8Test.java
Due to a bug, the `hl.fl` parameter **did not work at all** in previous versions, the only reason we didn't notice this is because all the tests and sample configurations used the `df` parameter, to which Solr falls back to if no `hl.fl` is defined.
> Fix hl.fl parameter handling

- pom.xml
- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrEscapedTest.java
Previously, we did not unescape XML-encoded character entities in the `text` field of each snippet hit, that is, the text would be `&#x17f;alle du divan` instead of `ſalle du divan`.
This PR remedies this for all supported formats.
> Unescape text in snippet hits

- docs/indexing.md
- docs/installation.md
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/util/SourcePointer.java
Profiling revealed that a lot of time was spent on mapping the input `byte` offsets for the source pointer regions to target `char` offsets. There's no way of getting around this with UTF8-encoded source documents, but for ASCII-only source files we can skip the process.
To this end, a new option is added to the source pointer format: Users can now include the `{ascii}` string after the path and before any regions to indicate to the plugin that the source file at the location is encoded in ASCII and it is safe to skip the offset mapping.
> Add optimization for ASCII-only input documents

- docs/formats.md
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrPassageFormatter.java
Previously we only supported getting the page identifier from the `id` HTML attribute or the `ppageno` hOCR property. This PR adds support for the [`x_source`](http://kba.cloud/hocr-spec/1.2/#x_source) hOCR property to support more use cases.
> hocr: Add support for retrieving page id from `x_source` property

- .gitlab-ci.yml
- integration-tests/run.sh
- integration-tests/test.py
This should ensure that we have no regressions in compatibility with legacy versions in the future.
> CI: Run legacy integration tests in CI

- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/util/OcrPage.java
- src/main/java/de/digitalcollections/solrocr/util/SourcePointer.java
**Error Handling**
Previously the plugin would crash the complete query in case highlighting failed. This PR changes this so only highlighting for the faulty field is skipped and the rest of the query can continue unimpeded. For the problematic field, a message with exception details is logged on the `ERROR` level so admins can analyze the error after the fact.
**Stricter Check of Page Identifiers**
Previously the code was conflicting in whether page identifiers were required or not (the docs said they were, while parts of the code implemented a fallback mechanism). This is now changed, a parsed page must **always** have an identifier (as specified in the format documentation) or the highlighting will fail.
**Assorted Bugfixes**
- Increased sample size for OCR format detection. 2k was too …
> Better error handling, stricter check of page identifiers and assorted bugfixes

- src/main/java/de/digitalcollections/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/util/FileBytesCharIterator.java
- src/main/java/de/digitalcollections/solrocr/util/IterableCharSequence.java
- src/main/java/de/digitalcollections/solrocr/util/MultiFileBytesCharIterator.java
- src/main/java/de/digitalcollections/solrocr/util/PageCacheWarmer.java
- src/test/java/de/digitalcollections/solrocr/formats/hocr/HocrClassBreakIteratorTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/CustomThreadsFilter.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrTest.java
- src/test/java/de/digitalcollections/solrocr/util/ContextBreakIteratorTest.java
- src/test/java/de/digitalcollections/solrocr/util/FileBytesCharIteratorTest.java
- src/test/java/de/digitalcollections/solrocr/util/MultiFileBytesCharIteratorTest.java
- src/test/java/de/digitalcollections/solrocr/util/TagBreakIteratorTest.java
This is a relatively hacky way to implement the issues raised in #64.
This PR adds a utility class to concurrently "warm" the OS page cache with files that will be used for highlighting.
This should significantly reduce the I/O latency during the sequential highlighting process, especially when using a network storage layer or a RAID system.
The idea is that a lot of storage layers can benefit from parallel I/O. Unfortunately, snippet generation with the current UHighlighter approach is strongly sequential, which means we give away a lot of potential performance, since we're limited by the I/O latency of the underlying storage layer. By pre-reading the data we might need in a concurrent way, we pre-populate the operating system's page cache, so any I/O performed by the snippet generation …
> Add concurrent page cache warming to reduce IO latency

- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightComponent.java
- src/main/java/de/digitalcollections/solrocr/util/PageCacheWarmer.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrTest.java
Adds a new `CloseHook` during plugin initialization to shut down the page cache warmer threads after closing the core. This should stop threads from hanging around and also allow us to get rid of the custom thread leak control checks in the unit tests. Also gets rid of a Guava dependency.
> Fix cache warmer shutdown

- docs/query.md
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlightingTimeout.java
- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightComponent.java
- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightParams.java
- src/main/java/de/digitalcollections/solrocr/solr/SolrOcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/util/ExitingIterCharSeq.java
- src/main/java/de/digitalcollections/solrocr/util/HighlightTimeout.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
The timeout will be checked during the most taxing part of the highlighting process, i.e. while reading the input OCR files from disk. If the timeout is encountered, highlighting for the current and any
further documents is cancelled and the highlighting terminated. Any snippets for documents that were handled before the timeout will be included in the response. The `responseHeader` will indicate the
partiality of the results with the `partialOcrHighlights` flag.
> Add `hl.ocr.timeAllowed` parameter to limit highlighting time

- pom.xml
- src/main/java/de/digitalcollections/solrocr/util/PageCacheWarmer.java
- Previously we assumed that all FileSources had `regions`. This is not true for files that are supposed to be read whole, so we use a fake region in this case now.
- Our previous reads from the file all were effectively NOPs, since we never cleared the underlying buffer. This is now fixed.
> Fix bug in page cache pre-warming.

- src/main/java/de/digitalcollections/solrocr/iter/MultiFileBytesCharIterator.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
Previously we'd just let the channels be GCed without properly closing them. A previous PR (!90) already added an `AutoCloseable` implementation for `FileBytesCharIterator`. This PR adds it for
`MultiFileBytesCharIterator` as well and adds the actualy closing to the `OcrFieldHighlighter` class.
> Close file channels after highlighting.

- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoPassageFormatter.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/resources/data/alto_float.xml
Relates to https://github.com/dbmdz/solr-ocrhighlighting/issues/93
This PR allows the retrieval of word coordinates that have been encoded with float values in ALTO files by converting these values to integers. The approach taken requires Java 7+ and has the same effect as Math.floor(). The conversion applies to all coordinates and may have a minor performance impact.
The PR also adds a test and a new resource file.
> Adds support for ALTO coordinates expressed as floats.

- docs/changes.md
- docs/index.md
- docs/query.md
- example/frontend/index.js
- example/frontend/package-lock.json
- example/frontend/package.json
- integration-tests/test.py
- src/main/java/de/digitalcollections/solrocr/formats/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/model/OcrBox.java
- src/main/java/de/digitalcollections/solrocr/model/OcrSnippet.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiTest.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrTest.java
Previously only regions would be referenced by their index, now this also applies to pages.
Before:
```json
{
"pages": [
{ "id": "page_380", "width": 1436, "height": 2427 }
],
"regions": [
{ "ulx": 196, "uly": 1703, "lrx": 1232, "lry": 1968, "page": "page_380" }
]
}
```
After:
```json
{
"pages": [
{ "id": "page_380", "width": 1436, "height": 2427 }
],
"regions": [
{ "ulx": 196, "uly": 1703, "lrx": 1232, "lry": 1968, "pageIdx": 0 }
]
}
```
This also renames the `regionIdx` field on Highlight objects to `parentRegionIdx` to make it semantically clearer what is being referenced.
> Change API to use indicies for both page and region references

- example/docker-compose.yml
- example/frontend/index.js
- example/frontend/package-lock.json
- example/frontend/package.json
- example/frontend/style.css
- example/iiif-prezi/main.py
- example/solr/install-plugin.sh
- integration-tests/test.py
- src/main/java/de/digitalcollections/solrocr/formats/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/model/OcrBox.java
- src/main/java/de/digitalcollections/solrocr/model/OcrSnippet.java
- src/main/java/de/digitalcollections/solrocr/model/SourcePointer.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
This PR got a bit out of hand since I was discovering  bugs left and right during testing of the initial "regions should carry their text" feature. But here we go:
1. Every region now carries the highlighted text it contains. This should allow for easy rendering of `alt` Attributes on region images without having to do clumsy text-processing of the complete snippet text.
2. The column splitting heuristic was tweaked to produce less false positives.
3. Subsequent passages with overlapping regions are now merged to form a bigger region. Previously this would result in snippets that contained some of the same lines as another snippet for the same document.
4. Better error messages during indexing. Previously users would just get a NPE message if a file was non-existant, now there's a …
> Add text to regions, bugfixes, update demo

- src/main/java/de/digitalcollections/solrocr/formats/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/model/OcrBox.java
Previously, highlight spans that crossed pages were not correctly split into separate highlight regions since we did not compare their respective pages during merging.
> Fix highlight merging

- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/util/Utf8.java
- src/test/java/de/digitalcollections/solrocr/lucene/ExternalUtf8ContentFilterTest.java
Previously we would read the source regions with a single `FileChannel.read` call into a `byte[]` buffer to map UTF-8 byte offsets to UTF-16 char offsets. In a test run with a few hundred thousand documents it turned out that this naive approach used excessive memory, leading to OOM errors when multiple large documents were indexed in parallel.
The offset mapper now reads the files in fixed chunks of 1MiB, re-using the (now off-heap allocated) buffer for the duration of the document.
> Reduce memory consumption during indexing

- src/main/java/de/digitalcollections/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/de/digitalcollections/solrocr/model/OcrSnippet.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoMultiTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
Previously snippets were not explicitly ordered, which resulted in different top-n snippets when changing the number of snippets returned. We now sort the snippets by their relevance score in descending order, i.e. the most relevant snippets will the the first in the list.
> Sort snippets by their descending score.

- docs/query.md
- src/main/java/de/digitalcollections/solrocr/formats/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoFormat.java
- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrFormat.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/mini/MiniOcrFormat.java
- src/main/java/de/digitalcollections/solrocr/formats/mini/MiniOcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/model/OcrBox.java
- src/main/java/de/digitalcollections/solrocr/model/OcrFormat.java
- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightParams.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
Previously, it was sometimes imposible to map the `<em>...</em>` spans in the text snippets to the highlight boxes. This was due to an overly aggressive merging strategy, that has now been fixed.
Additionally, this PR introduces a new parameter `hl.ocr.alignSpans` (that is disabled by default) that forces text spans to conform to word boundaries as set by the OCR. This has the effect of aligning text and image spans so they both contain the exact same text.
> Improve alignment between text and image spans (fixes #120)

- src/main/java/de/digitalcollections/solrocr/formats/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/model/OcrBox.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
Previously only the whole snippet text would be dehyhenated, owing to the fact that we only considered the (potentially hyphenated)
surface-form for generating the region text. We now track if a word is hyphenated during parsing of ALTO documents.
> Dehyphenate region text for ALTO

- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightComponent.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
This was broken before, due to a bad check in the shard collection/response finalization phase.
This commit also adds tests for regular and combined regular/ocr highlighting to the non-distributed integration tests.
> Fix regular highlighting in distributed setup.

- src/main/java/de/digitalcollections/solrocr/formats/OcrParser.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrParser.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/SanitizingXmlFilter.java
- src/main/java/de/digitalcollections/solrocr/reader/PeekingReader.java
- src/main/java/de/digitalcollections/solrocr/util/SourceAwareReader.java
- src/test/java/de/digitalcollections/solrocr/formats/hocr/HocrParserTest.java
- src/test/java/de/digitalcollections/solrocr/lucene/ExternalUtf8ContentFilterTest.java
- src/test/java/de/digitalcollections/solrocr/lucene/SanitizingXmlFilterTest.java
- src/test/java/de/digitalcollections/solrocr/util/PeekingReaderTest.java
- New `fixMarkup` parameter for `OcrCharFilterFactory` that enables code branches that try to "fix" broken/invalid markup. These fixes come with a bit of a performance hit and are thus disabled by default, since most users will have no need for them. The fixes that  are attempted are:
* Unescaped pointy (`<>`) brackets
* Illegal/partial entity declarations (i.e. caused by unescaped `&`)
- Errors raised during indexing will now always include the  source pointer of the document that caused the crash, which should help greatly with debugging
> More fixes for bad markup, better error reporting

- docs/query.md
- src/main/java/de/digitalcollections/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightParams.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
Setting this option to `off` or `false` will make sure that the passages are simply returned in order of their occurrence in the input document, and not based on their relevancy score in relation to the document.
> Add new `hl.ocr.scorePassages` parameter to toggle passage scoring (#151)

- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoParser.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrParser.java
- src/main/java/de/digitalcollections/solrocr/formats/miniocr/MiniOcrParser.java
Previously we'd bail with an exception (with a helpful message for hOCR/ALTO, with an ugly NPE for MiniOCR).
I think a few bad words shouldn't cause the whole query to fail, with this PR the missing coordinates will now be just `-1` and the process can continue.
> Be more tolerant of incomplete bounding boxes during parsing (#154)

- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilterFactory.java
Previously this would cause an error since the plugin wasn't able to determine an OCR format from the empty string, we now simply forward the empty string to the rest of the analysis chain.
> Handle empty field values during indexing.

- docs/query.md
- src/main/java/de/digitalcollections/solrocr/solr/OcrHighlightComponent.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
This was an ugly limitation of the previous version, due to which users had to always explicitly pass a list of 'regular' highlighting fields via `hl.fl`. A refactoring of the `OcrHighlightComponent` allows us to remedy this.
The fix is a bit hacky, but it works reliably: When we detect that highlighting is enabled, but no `hl.fl` parameter was passed (i.e. the highlighter will automatically highlight all stored fields), we create a custom explicit `hl.fl` parameter at runtime, that includes all of the default highlight fields, except for those fields contained in the `hl.ocr.fl` field set.
> Fix implicit default highlighting fields (implements #152).

- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoParser.java
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrParser.java
- src/main/java/de/digitalcollections/solrocr/formats/miniocr/MiniOcrParser.java
- src/test/java/de/digitalcollections/solrocr/formats/alto/AltoParserTest.java
- src/test/java/de/digitalcollections/solrocr/formats/hocr/HocrParserTest.java
The plugin would throw an error when a document would have no usable OCR content at all (e.g. with a single-page document that only contains an empty page).
This has now been fixed for all formats.
> Fix handling of documents with no content (fixes #163)

- integration-tests/data/hocr.html
- src/main/java/de/digitalcollections/solrocr/formats/hocr/HocrParser.java
- src/test/java/de/digitalcollections/solrocr/formats/hocr/HocrParserTest.java
This PR fixes a bug, when an empty box element such as:
```xml
<span class="ocrx_word" title="bbox 1268 1443 1276 1449;x_wconf 75"/>
```
occurs in the document. Unfortunately, all following boxes after an empty box won't be correctly parsed (process is stopped).
This PR will skip empty boxes (and reads the next element) to fix this problem.
> Skip empty boxes

- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/reader/PeekingReader.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
We had various spots that didn't handle empty documents very well, this has now been fixed.
> Fix indexing of OCR fields that only contain an empty string (fixes #167)

- pom.xml
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/reader/LegacyBaseCompositeReader.java
The API for `BaseCompositeReader` changed, so we had to vendor in a backport of the Lucene 8.8 implementation to maintain support for earlier Solr versions.
Currently the integration tests don't yet run under 8.9 since the official Docker image for 8.9 has not yet been released, this will be amended once it's out (shouldn't be too long now: https://github.com/docker-solr/docker-solr/pull/380)
> Add support for Solr 8.9.

- pom.xml
Release version including various fixes:
- #163 Documents with no Content
- #171 Indexing documents with elements that contain only an empty string
- #173 Empty OCR highlighting snippets
> Bump version to 0.7.0

- src/main/java/de/digitalcollections/solrocr/formats/alto/AltoFormat.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/SanitizingXmlFilter.java
- src/main/java/de/digitalcollections/solrocr/reader/LegacyBaseCompositeReader.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/resources/data/alto_namespaced.xml
Previously we didn't support namespaced ALTO XML since our heuristics for detecting ALTO didn't consider them. This PR remedies that and expands the XML sanitizer to not consider namespaces as illegal tags.
> Add support for namespaced ALTO XML (fixes #191)

- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
Trying to highlight empty snippets (or snippets where no format could be determined) would lead to a RTE before, we now just skip the document.
> Don't abort when trying to highlight empty snippets, skip instead (fixes #200)

- src/main/java/de/digitalcollections/solrocr/formats/OcrParser.java
- src/main/java/de/digitalcollections/solrocr/iter/ExitingIterCharSeq.java
- src/main/java/de/digitalcollections/solrocr/iter/MultiFileBytesCharIterator.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrPassageFormatter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/SanitizingXmlFilter.java
- src/main/java/de/digitalcollections/solrocr/model/SourcePointer.java
- src/main/java/de/digitalcollections/solrocr/reader/MultiFileReader.java
- src/test/java/de/digitalcollections/solrocr/solr/AltoTest.java
- src/test/java/de/digitalcollections/solrocr/solr/HocrTest.java
- src/test/java/de/digitalcollections/solrocr/util/MiniOcrByteOffsetsParser.java
https://github.com/policeman-tools/forbidden-apis
This includes:
- Explicitly specify locale for APIs that use `Locale.defaultLocale()` implicitly to avoid bugs caused by non-US locales
- Prefer `trySetAccessible()` on Java 9 over `setAccessible(true)` on earlier Java versions
Unfortunately we could not add this check to the CI setup, since we have one spot where we deliberatly use a deprecated API that uses the default locale for performance reasons ([`FileBytesCharIterator#getSubSequence(int, int, bool)`](https://github.com/dbmdz/solr-ocrhighlighting/blob/main/src/main/java/de/digitalcollections/solrocr/iter/FileBytesCharIterator.java#L138-L144)).
> Fix issues identified by `policeman-tools/forbidden-apis`

- pom.xml
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/test/resources/data/chronicling_hocr/seq-1.html
- src/test/resources/data/chronicling_hocr/seq-2.html
- src/test/resources/data/chronicling_hocr/seq-3.html
- src/test/resources/data/chronicling_hocr/seq-4.html
Previously parsing would crash when any file but the first in a
multi-file source pointer would start on a (legal, but unneeded)
UTF8 byte-order marker.
To fix this, when we detect a BOM in a file, we adjust source pointer
regions that start from the beginning of the file to not include the
UTF8 BOM.
> Fix multi-file parsing with UTF8 BOM (fixes #169)

- docs/alternatives.md
- pom.xml
- src/main/java/de/digitalcollections/solrocr/lucene/OcrAlternativesFilterFactory.java
- src/test/java/de/digitalcollections/solrocr/lucene/OcrAlternativesFilterTest.java
- Log a warning when truncated alternative readings are detected, urging the user to increase the maximum token length
- Update documentation for alternatives to include background on this
- Update documentation for alternatives with information on cases where alternatives are ignored
- Update test for alternative parsing with a token that exceeds the default length limit of 255
> Warn when alternatives are truncated, update docs (#226)

- src/main/java/de/digitalcollections/solrocr/formats/miniocr/MiniOcrFormat.java
Greetings. 
I am working on  a project that includes an option to submit MiniOcr files for indexing without lazy loading and I noticed that pages are not returned in query results when using this option. 
The cause is that the regex for matching the page element assumes double quoted xml. Unfortunately I submit single-quoted xml in a json post to solr.  This minor change is this PR fixes the problem. I hope you'll consider adding it. 
Thanks!
> Page regex updated to allow single quote.

- .github/workflows/ci.yml
- integration-tests/run.sh
- integration-tests/solr/core/v8/schema.xml
- integration-tests/solr/core/v8/solrconfig.xml
- integration-tests/solr/core/v9/schema.xml
- integration-tests/solr/core/v9/solrconfig.xml
- integration-tests/test.py
- pom.xml
- src/main/java/de/digitalcollections/solrocr/lucene/OcrAlternativesFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/OcrHighlighter.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/ExternalUtf8ContentFilterFactory.java
- src/main/java/de/digitalcollections/solrocr/lucene/filters/OcrCharFilterFactory.java
- src/test/java/de/digitalcollections/solrocr/solr/DistributedTest.java
- src/test/java/de/digitalcollections/solrocr/solr/MiniOcrTest.java
- src/test/resources/solr/distributed/solr.xml
- util/patch_solr78_bytecode.py
Add support for Solr 9.
From this change on, we will have to release two separate JAR files, one for Solr 9 and later, and one for Solr 8 and earlier. The reason for this is that with Lucene 9, the package path for `CharFilterFactory` has changed, which is something we can't work around with Reflection magic like we did so far. 
Additionally, `CloseHook` became an interface in Solr, instead of an abstract class, with the same problem.
So we now provide a script in `util/patch_solr78_bytecode.py` to create a Solr7/8 compatible JAR from one built against Solr 9.
We did not use ByteBuddy or ASM, since building multiple JARs from a single POM is a ridiculous pain, so this little Python script to do the neccessary bytecode manipulation manually seemed easier and simpler to maintain.
> Add support for Solr 9 while maintaining backwards-compatibility

- util/update_repo.py
Tool to update the Solr Plugin Repository at https://dbmdz.github.io/solr.
Needs the following secrets passed via environment variables:
- GH_DEPLOY_TOKEN: Token with permissions to push to the repository at github.com:dbmdz/dbmdz.github.io.git
- CERTIFICATE: PEM-encoded private key for signing artifacts in the repository, corresponding to the
repository's public key.
> Add tool to update plugin repository

- .github/workflows/ci.yml
- integration-tests/run.sh
- util/patch_solr78_bytecode.py
- Caching of build artifacts between steps works now
- Integration Tests are their own job now
- All dependencies updated to v3
- Bytecode patching performed as part of build step via CI
- Removed mkdocs deployment temporarily, will be added back again in a
separate change
- Fixed a bug in the bytecoder patcher, formatted with black
> Update CI setup

- example/docker-compose.yml
- example/frontend/Dockerfile
- example/frontend/index.js
- example/ingest.py
- example/solr/core/solrconfig.xml
- example/solr/install-plugin.sh
- Changed volume definitions to match the new container structure
- Changed Image API endpoints and Image API requests to match updated image server at ocrhl.jbaiter.de
- Pinned version of `node:alpine` frontend build container to fix broken builds
- Remove service worker of frontend code after build to fix strange routing behavior in the frontend
- Fix bug in ingest script to handle changed return API from newer versions of Python's `tarfile` API
> Update example setup to Solr 9

- .github/workflows/ci.yml
- docs/alternatives.md
- docs/changes.md
- docs/example.md
- docs/formats.md
- docs/index.md
- docs/indexing.md
- docs/installation.md
- docs/performance.md
- mkdocs.yml
- Updated CI config to publish documentation to gh-pages
- Updated namespaces in examples to reflect recent change
- Updated changelog to always have a link to the GitHub release page
- Added references to the new package management repository
- mkdocs-material allows us to highlight individual lines in code
blocks, which should help with the readability of the configuration
snippets.
> Update docs, use material theme

- src/main/java/com/github/dbmdz/solrocr/solr/SolrOcrHighlighter.java
Previously we'd just show no highlighting without any indication as to why this was the case.
Hopefully helps some users who missed the fact that OCR fields have to be stored in the documentation.
> Warn when OCR highlighting requested, but no matching stored fields are found

- docs/performance.md
- docs/query.md
- pom.xml
- src/main/java/com/github/dbmdz/solrocr/model/SourcePointer.java
- src/main/java/com/github/dbmdz/solrocr/solr/OcrHighlightParams.java
- src/main/java/solrocr/OcrHighlightComponent.java
- src/main/java/solrocr/OcrHighlighter.java
Sometimes users may want to set parameters differently between regular highlighting and OCR highlighting. This is already possible for some parameters (`hl.score.{k1,b,pivot}`, `hl.weightMatches`) via the `f.<field-name>.<param>` syntax, but for more global values this was impossible.
This PR introduces a few new `hl.ocr.*` parameters that can be used to override their corresponding `hl.*` counterparts:
- `hl.ocr.q`
- `hl.ocr.qparser`
- `hl.ocr.tag.pre`
- `hl.ocr.tag.post`
Additionally, the docs were updated in some places.
> Allow overriding of some `hl.*` parameters

- src/main/java/com/github/dbmdz/solrocr/formats/hocr/HocrParser.java
- src/test/java/com/github/dbmdz/solrocr/formats/hocr/HocrParserTest.java
- src/test/resources/data/empty_words_bug.html
Hi,
we have seen a parser bug when trying to read an hOCR that contains empty words, such as:
```xml
<div class="ocrx_block" title="bbox 106 887 488 934">
<p class="ocr_par" title="bbox 106 887 488 934">
<span class="ocr_line" title="bbox 106 887 107 888">
<span class="ocrx_word" title="bbox 106 887 107 888" />
</span>
</p>
</div>
```
Thus, this PR:
* introduces a bug fix in the hOCR logic
* adds an extensive unit test
> hOCR: empty word fix

- src/main/java/com/github/dbmdz/solrocr/formats/hocr/HocrClassBreakLocator.java
- src/main/java/com/github/dbmdz/solrocr/iter/BaseBreakLocator.java
- src/main/java/com/github/dbmdz/solrocr/model/OcrFormat.java
- src/main/java/solrocr/OcrHighlighter.java
- src/test/java/com/github/dbmdz/solrocr/solr/HocrTest.java
- src/test/resources/data/issue_288.hocr
When locating breaks based on hOCR classes, we read the input in blocks of 64k chars. Previously, due to an error in the looping logic, we would not actually read any blocks besides the first one  and set the limit to the end of the first block. This should be fixed now, more blocks are read as needed.
> Fix incomplete forward passes in HocrClassBreakLocator (fixes #288)

- src/main/java/com/github/dbmdz/solrocr/formats/OcrParser.java
- src/main/java/com/github/dbmdz/solrocr/formats/alto/AltoParser.java
- src/main/java/com/github/dbmdz/solrocr/formats/hocr/HocrParser.java
- src/main/java/com/github/dbmdz/solrocr/formats/miniocr/MiniOcrParser.java
- src/main/java/com/github/dbmdz/solrocr/iter/BaseBreakLocator.java
- src/test/java/com/github/dbmdz/solrocr/solr/HocrTest.java
For some very broken-but-valid OCR files this could lead to incredibly deep stacks, so we better switch to an iterative solution.
> Refactor skipping of ignored words to not use recursion.

- src/test/java/com/github/dbmdz/solrocr/solr/HocrTest.java
Had a TODO in our Solr setup that these two parameters seemed to be broken, so I added tests for them.
Turns out they're not broken and work as expected 😅
> Add tests for hl.ocr.q and hl.ocr.qparser parameters

- integration-tests/run.sh
- pom.xml
- src/main/java/com/github/dbmdz/solrocr/reader/LegacyBaseCompositeReader.java
- src/main/java/com/github/dbmdz/solrocr/util/HighlightTimeout.java
- Implemented missing methods `BaseCompositeReader` API introduced in Lucene 9.8
- Removed `@Override` on `HighlightTimeout#isTimeoutEnabled`, seems to have been removed from the `QueryTimeout` interface
Luckily no bytecode patching neccessary, integration tests succeed for all supported Solr versions all the way back to Solr 7.7 🥳
> Fix compatibility with Solr 9.4 and Lucene 9.8

- src/main/java/solrocr/OcrHighlightComponent.java
Looks like there's a bug in Solr where when no highlighting field can be determined (from `hl.fl` or the `df` defined for the query parser), the set of highlight fields will contain a single `null` value that triggers an exception down the line, causing the highlight component to fail and the response to return with a 400 error code.
The workaround is to simply set the `hl.fl` paremter for the regular highlighter explicitly, and excluding the `null` value there.
> Fix regular highlighting in case no hl field can be determined (fixes #396)

- util/update_repo.py
When a version fails to build, skip it instead of failing the whole build.
> Make update_repo.py more robust

- src/main/java/com/github/dbmdz/solrocr/iter/MultiFileBytesCharIterator.java
- src/main/java/com/github/dbmdz/solrocr/lucene/OcrPassageFormatter.java
- src/test/java/com/github/dbmdz/solrocr/solr/AltoMultiTest.java
- src/test/resources/data/alto_concat_421/007.xml
- src/test/resources/data/alto_concat_421/009.xml
- src/test/resources/data/alto_concat_421/017.xml
- src/test/resources/data/alto_concat_421/019.xml
- src/test/resources/data/alto_concat_421/020.xml
- src/test/resources/data/alto_concat_421/046.xml
- src/test/resources/data/alto_concat_421/052.xml
The code previously only considered the case of two concatenated files when reading from a concatenated source pointer. This has now been fixed to allow an arbitrary number of files between the start and end offsets.
> Fix passage building across more than two concatenated files (fixes #421)

- src/main/java/com/github/dbmdz/solrocr/model/SourcePointer.java
- src/main/java/com/github/dbmdz/solrocr/solr/SolrOcrHighlighter.java
- src/main/java/solrocr/OcrHighlighter.java
- src/test/java/com/github/dbmdz/solrocr/solr/DistributedTest.java
- src/test/java/com/github/dbmdz/solrocr/solr/HocrTest.java
Instead just skip the field and continue with the rest.
> Don't fail the whole request when a source pointer can't be read.

- example/bench.py
- src/main/java/com/github/dbmdz/solrocr/lucene/OcrFieldHighlighter.java
- src/main/java/solrocr/OcrHighlighter.java
Turns out we were mixing up the counts between multiple documents by keying according to the leaf-reader-relativ docId instead of the index-absolute docId. This led to differing total counts between different runs of one and the same query, which is how this was discovered. Total counts should be accurate now.
> Fix bad total snippets counts.

- src/main/java/com/github/dbmdz/solrocr/lucene/filters/ByteSeekableReader.java
- src/main/java/com/github/dbmdz/solrocr/lucene/filters/ExternalUtf8ContentFilter.java
- src/main/java/com/github/dbmdz/solrocr/model/SourcePointer.java
- src/main/java/com/github/dbmdz/solrocr/reader/SourceReader.java
- src/main/java/com/github/dbmdz/solrocr/reader/StreamDecoder.java
- src/main/java/solrocr/ExternalUtf8ContentFilterFactory.java
- src/test/java/com/github/dbmdz/solrocr/lucene/ExternalUtf8ContentFilterTest.java
Instead, calculate difference while we read through the input during parsing. This saves us a whole pass through the input files, which should improve performance for non-filesystem based sources (where we don't have the page cache to help us out).
> ExternalUtf8ContentFilterFactory: Don't convert pointer offsets to char

- pom.xml
- src/main/java/com/github/dbmdz/solrocr/formats/miniocr/MiniOcrFormat.java
The parsing method is now tolerant of differing attribute order and the presence of extra attributes that we don't care about.
> miniocr: Make page fragment parsing more robust (#447)

- docs/formats.md
- util/miniocr.py
Uses only Python 3 stdlib packages, implements the ALTO and hOCR parsers as generators that yield abstract OCR events, MiniOCR generation then consumes these events and yields markup chunks that can be written to a file.
> Add tool to convert ALTO and hOCR to MiniOCR (implements #447)

- docs/installation.md
- integration-tests/run.sh
- pom.xml
- src/main/java/com/github/dbmdz/solrocr/formats/miniocr/MiniOcrFormat.java
- src/main/java/com/github/dbmdz/solrocr/lucene/filters/SanitizingXmlFilter.java
- src/main/java/com/github/dbmdz/solrocr/reader/BaseSourceReader.java
- src/main/java/com/github/dbmdz/solrocr/reader/StreamDecoder.java
- src/main/java/solrocr/OcrHighlighter.java
- `<lib>` directives in the core config need to be explicitely enabled (needed for integration tests)
- `IndexSearcher.storedFields()` is now used for Lucene versions >= 9.5 instead of the deprecated `doc` method for retrieving stored field values.
- Update code formatter
- Remove `OcrHighlighter#getTermVectors()`, no longer needed to fulfill the interface
> Fix compatibility with Solr 9.8

- src/main/java/solrocr/OcrHighlightComponent.java
We falsely assumed that the `ocrHighlighting` was always set on a response where the feature was enabled, but this was not the case when the request processing was previously stopped due to limits.
> Fix errors when a partial response is received during distributed request processing

- README.md
- docs/changes.md
- pom.xml
**Changed**
- Respect global request limits (time, memory, cpu) from the [`*allowed` Solr query parameters][1] in addition to our own OCR-specific limit
**Fixed**
- Highlighting responses that are partial by the time they hit the highlighting stage during distributed request processing resulted in errors, this has been fixed.
> Release 0.9.3: Support for limits API and fix for partial responses

- README.md
- docs/installation.md
- pom.xml
- util/update_repo.py
The version constraint for the releases for Solr 9.x were pinned to 9.0, which caused issues. The constraints have now been adjusted to match the actual compatibility between plugin and Solr versions.
Additionally, the documentation was updated to point to the correct repository URL for Solr versions 7.x and 8.x.
> Fix version constraints for package repository.

- docs/formats.md
- docs/indexing.md
See #479, non-unique page identifiers and ALTO with namespace prefixes breaks our String-based break location algorithm.
> Update documentation with requirements for ALTO and page identifiers

- src/main/java/com/github/dbmdz/solrocr/lucene/OcrFieldHighlighter.java
- src/test/java/com/github/dbmdz/solrocr/solr/HocrTest.java
The intention for this feature was to return the snippets in their order of appearance in the highlighted document, with the earliest matches coming first. Due to a mistake in the way this was implemented, the order was correct, but users would get the *last* matches in the document, not the *first* matches in the document.
> Fix order of snippets when highlighting with scoring disabled.
